CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY,
  name VARCHAR(13) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  birthday DATE DEFAULT '1990-01-01',
  gender INTEGER DEFAULT 0,
  creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  banned INTEGER DEFAULT 0,
  loggedin INTEGER DEFAULT 0,
  tos INTEGER DEFAULT 1
);
